
#General settings
[general]
	#Should this mod add some of its items (CORN!!!) as extra chest loot across Minecraft?
	genCornLootModifier = false
	#Generate wild corn on cold biomes (temperature between 0.0 and 1.0)
	genWildCorn = false
	#Chance of generating clusters. Smaller value = more frequent.
	#Range: > 0
	chance = 30

